bootstrap.servers=kafka:9092
kafka.cluster.id=ciWo7IWazngRchmPES6q5A==
schema.registry.url=http://schema-registry:8081
group.id=cflt-meetup-cg
iceberg.catalog.uri=http://iceberg-rest:8181/
iceberg.catalog.warehouse=s3://warehouse/
iceberg.catalog.access.key=admin
iceberg.catalog.secret.key=password
iceberg.catalog.client.region=us-east-1
iceberg.catalog.s3.endpoint=http://minio:9000
iceberg.database=meetup