{
  "type": "record",
  "name": "TransactionsV2",
  "namespace": "org.apache.flink.playground.datagen.model",
  "fields": [
    { "name": "transactionId", "type": "string" },
    { "name": "accountId", "type": "long" },
    { "name": "amount", "type": "double" },
    { "name": "currency", "type": "string" },
    { "name": "timestamp", "type": { "type": "long", "logicalType": "timestamp-millis" } },
    { "name": "status", "type": { "type": "enum", "name": "Status", "symbols": ["PENDING", "COMPLETED", "FAILED"] } },
    { "name": "description", "type": ["null", "string"], "default": null },
    { "name": "coRelationId", "type": ["null", "string"], "default": null }
  ]
}